// начальные фильмы
export const initialMovies = [
  {
    nameRU: '33 слова о дизайне',
    image: new URL('../images/movies/movie1.png', import.meta.url),
    duration: '1ч 47м',
    movieId: 1,
    isSaved: true,
  },
  {
    nameRU: 'Киноальманах «100 лет дизайна»',
    image: new URL('../images/movies/movie2.png', import.meta.url),
    duration: '1ч 3м',
    movieId: 2,
    isSaved: true,
  },
  {
    nameRU: 'В погоне за Бенкси',
    image: new URL('../images/movies/movie3.png', import.meta.url),
    duration: '1ч 42м',
    movieId: 3,
    isSaved: false,
  },
  {
    nameRU: 'Баския: Взрыв реальности',
    image: new URL('../images/movies/movie4.png', import.meta.url),
    duration: '1ч 21м',
    movieId: 4,
    isSaved: false,
  },
  {
    nameRU: 'Бег это свобода',
    image: new URL('../images/movies/movie5.png', import.meta.url),
    duration: '1ч 44м',
    movieId: 5,
    isSaved: false,
  },
  {
    nameRU: 'Книготорговцы',
    image: new URL('../images/movies/movie6.png', import.meta.url),
    duration: '1ч 37м',
    movieId: 6,
    isSaved: false,
  },
  {
    nameRU: 'Когда я думаю о Германии ночью',
    image: new URL('../images/movies/movie7.png', import.meta.url),
    duration: '1ч 56м',
    movieId: 7,
    isSaved: false,
  },
  {
    nameRU: 'Gimme Danger: История Игги и The Stooge...',
    image: new URL('../images/movies/movie8.png', import.meta.url),
    duration: '1ч 59м',
    movieId: 8,
    isSaved: false,
  },
  {
    nameRU: 'Дженис: Маленькая девочка грустит',
    image: new URL('../images/movies/movie9.png', import.meta.url),
    duration: '1ч 42м',
    movieId: 9,
    isSaved: false,
  },
  {
    nameRU: 'Соберись перед прыжком',
    image: new URL('../images/movies/movie10.png', import.meta.url),
    duration: '1ч 10м',
    movieId: 10,
    isSaved: false,
  },
  {
    nameRU: 'Пи Джей Харви: A dog called money',
    image: new URL('../images/movies/movie11.png', import.meta.url),
    duration: '1ч 4м',
    movieId: 11,
    isSaved: false,
  },
  {
    nameRU: 'По волнам: Искусство звука в кино',
    image: new URL('../images/movies/movie12.png', import.meta.url),
    duration: '1ч 7м',
    movieId: 12,
    isSaved: false,
  },
];